projects:
  Insta:
    schemaPath: amplify/backend/api/Insta/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-west-3
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
